#
# CI VARS: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
#
stages:
  - deploy

apply:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cluster-integration/cluster-applications:latest
  environment:
    name: production
  script:
    - helmfile --file $CI_PROJECT_DIR/helm/helmfile.yaml apply --suppress-secrets
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
